[versions]
bouncycastle = "1.67"
chucker = "3.2.0"
google_auto_value = "1.7"
irradia_mime = "1.1.1"
jackson = "2.10.0"
jackson_kotlin = "2.9.9"
javax_annotations = "1.2-b01"
jcip_annotations = "1.0-1"
joda_time = "2.9.9"
junit = "5.7.0"
kotlin = "1.4.32"
logback_android = "1.1.1-6"
logback_classic = "1.2.3"
mockito_android = "2.22.0"
mockito_kotlin = "2.2.0"
mockwebserver = "4.9.0"
okhttp = "4.9.0"
slf4j_api = "1.7.25"

[libraries]
bouncycastle = { module = "org.bouncycastle:bcpg-jdk15on", version.ref = "bouncycastle" }
bouncycastle_PKI = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncycastle" }
bouncycastle_TLS = { module = "org.bouncycastle:bctls-jdk15on", version.ref = "bouncycastle" }
chucker = { module = "com.github.ChuckerTeam.Chucker:library", version.ref = "chucker" }
google_auto_value = { module = "com.google.auto.value:auto-value-annotations", version.ref = "google_auto_value" }
google_auto_value_processor = { module = "com.google.auto.value:auto-value", version.ref = "google_auto_value" }
irradia_mime_api = { module = "one.irradia.mime:one.irradia.mime.api", version.ref = "irradia_mime" }
irradia_mime_vanilla = { module = "one.irradia.mime:one.irradia.mime.vanilla", version.ref = "irradia_mime" }
jackson_core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson_databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson_kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson_kotlin" }
javax_annotation_api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax_annotations" }
jcip_annotations = { module = "com.github.stephenc.jcip:jcip-annotations", version.ref = "jcip_annotations" }
joda_time = { module = "joda-time:joda-time", version.ref = "joda_time" }
junit_jupiter_api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit_jupiter_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
kotlin_reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin_stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
logback_android_classic = { module = "com.github.tony19:logback-android-classic", version.ref = "logback_android" }
logback_android_core = { module = "com.github.tony19:logback-android-core", version.ref = "logback_android" }
logback_classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback_classic" }
mockito_android = { module = "org.mockito:mockito-android", version.ref = "mockito_android" }
mockito_kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockito_kotlin" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j_api" }
